name: Test Gemini IA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Interroga Gemini
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_API_KEY }}
          API_HOST: "://googleapis.com"
          API_PATH: "/v1beta/models/gemini-3.5-flash:generateContent"
        run: |
          curl -X POST "https://${API_HOST}${API_PATH}?key=${GEMINI_KEY}" \
          -H "Content-Type: application/json" \
          -d '{"contents": [{"parts":[{"text": "ciao"}]}]}'
