name: Test Gemini IA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Interroga Gemini
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          curl -X POST "https://googleapis.com{GEMINI_KEY}" \
          -H "Content-Type: application/json" \
          -d '{"contents": [{"parts":[{"text": "buongiorno"}]}]}'
